# -*- coding: utf-8 -*-
"""4_hybrid_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtdcrKMX2EvzrQ6XUHRwUpWdW9KBOqIY

## Building Hybrid Search in Qdrant
"""

!pip install -q qdrant-client[fastembed]

!pip install -U sentence-transformers transformers

from qdrant_client import QdrantClient
from google.colab import userdata

client = QdrantClient(
    location = "https://b9d13b33-842f-4f65-8d2b-de07f146ebea.europe-west3-0.gcp.cloud.qdrant.io",
    api_key = userdata.get("qdrant_api_key")
)

from qdrant_client import models

collection_name = "hybrid_seach_demo"

client.create_collection(
    collection_name = collection_name,
    vectors_config = {
        "dense": models.VectorParams(
            distance = models.Distance.COSINE,
            size = 384
        ),
    },
    sparse_vectors_config = {
        "sparse": models.SparseVectorParams(
            modifier = models.Modifier.IDF
        )
    }
)

"""### Upload the data into the collection"""

documents = [
    "Aged Gouda develops a crystalline texture and nutty flavor profile after 18 months of maturation.",
    "Mature Gouda cheese becomes grainy and develops a rich, buttery taste with extended aging.",
    "Brie cheese features a soft, creamy interior surrounded by an edible white rind.",
    "This French cheese has a flowing, buttery center encased in a bloomy white crust.",
    "Fresh mozzarella pairs beautifully with ripe tomatoes and basil leaves.",
    "Classic Margherita pizza topped with tomato sauce, mozzarella, and fresh basil.",
    "Parmesan requires at least 12 months of cave aging to develop its signature sharp taste.",
    "Parmigiano-Reggiano's distinctive piquant flavor comes from extended maturation in controlled environments.",
    "Grilled cheese sandwiches are the ultimate American comfort food for cold winter days.",
    "Croque Monsieur combines ham and Gruyère in France's answer to the toasted cheese sandwich.",
]

import uuid

client.upsert(
    collection_name = collection_name,
    points = [
        models.PointStruct(
            id = uuid.uuid4().hex,
            vector = {
                "dense": models.Document(
                    text = doc,
                    model = "sentence-transformers/all-MiniLM-L6-v2"
                ),
                "sparse": models.Document(
                    text = doc,
                    model = "Qdrant/bm25"
                )
            },
            payload = {"text": doc},
        )
        for i, doc in enumerate(documents)
    ]
)

def dense_search(query: str) -> list[models.ScoredPoint]:
    response = client.query_points(
        collection_name = collection_name,
        query = models.Document(
            text = query,
            model = "sentence-transformers/all-MiniLM-L6-v2",
        ),
        using = "dense",
        limit = 3,
    )
    return response.points

def sparse_search(query: str) -> list[models.ScoredPoint]:
    response = client.query_points(
        collection_name = collection_name,
        query = models.Document(
            text = query,
            model = "Qdrant/bm25",
        ),
        using = "sparse",
        limit = 3,
    )
    return response.points

"""### Run both methods on same queries and validate the output"""

queries = [
    "nutty aged cheese",
    "soft French cheese",
    "pizza ingredients",
    "a good lunch"
]

for query in queries:
    print("Query:", query)

    dense_results = dense_search(query)
    print("Dense Results:")
    for result in dense_results:
        print("\t-", result.payload["text"], result.score)

    sparse_results = sparse_search(query)
    print("Sparse Results:")
    for result in sparse_results:
        print("\t-", result.payload["text"], result.score)

    print()

"""### Hybrid Search with Reciprocal Rank Fusion"""

def rrf_search(query: str) -> list[models.ScoredPoint]:
    response = client.query_points(
        collection_name=collection_name,
        prefetch=[
            models.Prefetch(
                query=models.Document(
                    text=query,
                    model="Qdrant/bm25",
                ),
                using="sparse",
                limit=3,
            ),
            models.Prefetch(
                query=models.Document(
                    text=query,
                    model="sentence-transformers/all-MiniLM-L6-v2",
                ),
                using="dense",
                limit=3,
            ),
        ],
        query=models.FusionQuery(fusion=models.Fusion.RRF),
        limit=3,
    )

    return response.points

for query in queries:
    print("Query:", query)

    rrf_results = rrf_search(query)
    print("RRF Results:")
    for result in rrf_results:
        print("\t-", result.payload["text"], result.score)

